
USE DATABASE Insurance_analytics;
USE SCHEMA LANDING_ZONE;

DROP TABLE landing_to_staging;

CREATE TABLE IF NOT EXISTS landing_to_staging( 
    landing_table STRING,
    staging_table STRING,
    LANDING_SCHEMA STRING,
    STAGING_SCHEMA STRING
); 

INSERT INTO landing_to_staging VALUES ('LNDING_CUSTOMER','STAGING_CUSTOMER','LANDING_ZONE','STAGING_ZONE');
INSERT INTO landing_to_staging VALUES ('LNDING_CLAIM','STAGING_CLAIM','LANDING_ZONE','STAGING_ZONE');
INSERT INTO landing_to_staging VALUES ('LNDING_POLICY','STAGING_POLICY','LANDING_ZONE','STAGING_ZONE');
INSERT INTO landing_to_staging VALUES ('LNDING_PRODUCT','STAGING_PRODUCT','LANDING_ZONE','STAGING_ZONE');
INSERT INTO landing_to_staging VALUES ('LNDING_SALES','STAGING_SALES','LANDING_ZONE','STAGING_ZONE');