drop database insurance_analytics;
Create database insurance_analytics;
use database insurance_analytics;
create schema landing_zone;
create schema staging_zone;
create schema ravault_zone;
create schema BUSINESSVAULT_ZONE;
create schema information_zone;
create schema consumption_zone;