
CREATE EVENT TABLE INSURANCE_ANALYTICS.LANDING_ZONE.my_events;
ALTER DATABASE INSURANCE_ANALYTICS SET EVENT_TABLE = INSURANCE_ANALYTICS.LANDING_ZONE.my_events;
ALTER database SET LOG_LEVEL = DEBUG;

ALTER PROCEDURE sp_load_landing_to_staging() SET AUTO_EVENT_LOGGING = 'ALL';
