name: Deploy Snowflake Database and Schema

on:
  push:
    branches:
      - sprint1  # Change this if needed
  workflow_dispatch:  # Allows manual execution from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y snowsql
    

      - name: Deploy Database and Schema
        run: |
          snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
          -u ${{ secrets.SNOWFLAKE_USER }} \
          -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
          -r ${{ secrets.SNOWFLAKE_ROLE }} \
          -f snowflake\create_b.sql
