---
name: Deploy  Database
on:
  push:
    branches:
      - sprint1
  workflow_dispatch: null
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install SnowSQL with Debugging
        run: |
          export SNOWSQL_DEST="$HOME/snowsql"
          export SNOWSQL_LOGIN_SHELL="$HOME/.bashrc"
          mkdir -p $HOME/snowsql
          cd $HOME/snowsql
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.24-linux_x86_64.bash
          chmod +x snowsql-1.2.24-linux_x86_64.bash
          ./snowsql-1.2.24-linux_x86_64.bash  --install-dir=$HOME/snowsql > install_log.txt 2>&1 || cat install_log.txt
          echo "$HOME/.snowsql/bin" >> $GITHUB_PATH  
    
      - name: Check OpenSSL
        run: |
          openssl version
          ls -l /usr/lib/x86_64-linux-gnu/libcrypto*
      - name: Check SnowSQL Installation
        run: |
          cd /home/runner/snowsql 
          ./snowsql --version    
      - name: Set Environment Variables
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}          
        run: |
          echo "SNOWSQL_PWD=${{ secrets.SNOWFLAKE_PASSWORD }}" >> $GITHUB_ENV         
      - name: Deploying Database  n and Schemas
        run: |
          export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
          cd /home/runner/snowsql
          ./snowsql \
          -a "${{ secrets.SNOWFLAKE_ACCOUNT }}" \
          -u "${{ secrets.SNOWFLAKE_USER }}" \
          -o log_level=DEBUG \
          -f "/home/runner/work/Insurance_analytics/create_db.sql"
        

